version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: rating_microservice
    networks:
      - my-network

  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-container
    restart: always
    ports:
      - "8090:8080"
    environment:
      - MYSQL_HOST=mysql-container
      - MYSQL_PORT=3306
      - MYSQL_DB_NAME=rating_microservice
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password123
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
